language: node_js
git:
  depth: 3
notifications:
  email: false
node_js:
  - "10"
services: docker
cache: yarn

env:
  global:
    # NPM_TOKEN
    - secure: "L/umajEryp4I1BSAbfQhwKhFcTfKFretCjrDawfzCj5RZdXpKc4s/5YqNHreDFrcccfKX22dEJjUMAqRUV9hHPP9wq+7GxFRK4RNsUwnTFFVPmxkEszchqZN8j7qKtGNkJ5R46roJNUTy9lhpeBRqE25xU96Z37a+EFJ5qPP1jmIT5P9l9U8wEBE6RE0BIyfpx9GzWOv7zBG0M7hNJWsZlU+Gm9Irn7US27kZ9sYOTBletWwy9C/FhTTZdDi9khN7NaS52AFK1806U4ChZSZv5ZyKxzmNIywM3fZDys1r0lXSVDyNVSepqFRsBXWvB25Fyq8y1BoZac6AYxtoF0YNPYUF78RiJobEI1VJXhL2gq1lye9O1o/IJfgEJ42bd3uC1zpdVqSARXosIjmGpASSKcFNLdhJEYd58sKzOxbYLCXVUxbkGY5LWpTPoUp/DEZuD0kkszGWtk/+rw/3TsBL2ZWlpdentauvZpVFF/+WyD+nNWkGFAM06jQRYtAdB+3+VJtXzQtXDdLgCcOpvH83JqDWyOKUSQWS2ePgvi+9i2rUhlfA8bVssB1Pr+Opnql8f5TH96JlGtPAX1uObxub6GjavayTc2fPHK52OGPDpP2FSoJ0k+9q5675EOdrPMN8XqSvCrullnCHMDZAnIxJwYn1OukgB50joTm77Afi2I="
    # GH_TOKEN
    - secure: "Nycvk6E3t+tHz6akzqZrGUTcboX7UXcPoAxDK7971c3XbWA9B9mI02t4R9AbuQLKwM4Z6ioCcRkWb6u1KPwUPlGPm3F8Ovoa7lmwUnDpoFsmBUSkwxgQ3Xb/O6EEL4xUFMqwvshm18K9pOC2UWZNr/a4XZVjmzRqPJwieKGbh0J72K0VEf7Dgie2NchDN/MSVf2pGHX8tHcZOLMn+lVcPYHreK4zb9Bipm/XZg7Hcb3bcqSCdiztSC7+V4uc1LisTVbiAigFK7IIMjODp0PAHBkr6/Sv3o+LxgM9pvH5Ety1jlimXq0WW5elX0B7B1IsZT4+wUUGtFH7v8fRi/1j8/1gynfqai/hetW41ta0ZdSroJZbPr7K39+FpodWnq6xai9xfAEhFITDT29hmvFVvlmZeH03OzhfKkhmN04JrobdV8ToIUa8KrE1Vq18IbS23ciLoPan0NbXiIZP3PW9e90e7OF1k6ssqBbgRQFF4d5k7GNaJDsyadGPHw7yIz4krCsknIO8W3HAnuWQkwRR2Pe71LtiBkIb1p42D6g6Ppba8iGK4DPcXSGYRg8RfVC5znAg6Zdhsjbx3t4fVK+UloWOkIalsDEbocfEpPZXP6m1iCxNIikXmUUM4iqFkgh8WHNL1n91LKFV2jCQ8yUjZAjPPc2seZy9Lw0dE3pKUbE="

script:
  - yarn validate
after_success:
  - yarn --silent nyc report --reporter=text-lcov | sed "s|/app|$(pwd)|" | ./node_modules/.bin/coveralls
  # Rebuild docs, only on master branch and not on pull requests
  - '[[ $TRAVIS_PULL_REQUEST = "false" && $TRAVIS_BRANCH = "master" ]] && yarn docs'

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    allow_empty_commit: true
    local_dir: docs
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: yarn semantic-release
    on:
      branch: master
