version: "3"
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/admin
  tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile-test
    environment:
      - NEO4J_URL=bolt://neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASS=admin
    command: yarn nyc --reporter=html --reporter=text-summary mocha src/*.spec.ts src/**/*.spec.ts tests/**/*.test.ts
    volumes:
      - ..:/app
      - /app/node_modules

